openapi: 3.0.1
info:
  title: Blocked clients API
  contact:
    email: valery.verevkina@gmail.com
  version: '1.0'
servers:
  - url: http://localhost:8080
tags:
  - name: Blocked clients
    description: Blocked clients API
paths:
  /api/v1/clients/unblock:
    post:
      tags:
        - Blocked clients
      summary: Unblock clients from the blocked list
      operationId: unblocks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnblockedClientsDto'
        required: true
      responses:
        '204':
          description: Clients successfully unblocked from the blocked list
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Service error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/clients/block:
    post:
      tags:
        - Blocked clients
      summary: Add to blocked list
      description: Adds list of clients to the blocked list.
      operationId: createBlockedClients
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AddBlockedClientDto'
        required: true
      responses:
        '204':
          description: Client successfully added to the blocked list
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Service error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/client/{clientId}/unblock:
    post:
      tags:
        - Blocked clients
      summary: Unblock thе client from the blocked list
      operationId: unblock
      parameters:
        - name: clientId
          in: path
          description: Внешний id клиента
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Client successfully unblocked from the blocked list
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Service error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/client/block:
    post:
      tags:
        - Blocked clients
      summary: Add to blocked list
      description: Adds a client to the blocked list.
      operationId: createBlockedClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddBlockedClientDto'
        required: true
      responses:
        '204':
          description: Client successfully added to the blocked list
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Service error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/blocked-clients/{clientId}:
    get:
      tags:
        - Blocked clients
      summary: Get the client from blocked list
      operationId: getInfo
      parameters:
        - name: clientId
          in: path
          description: Внешний id клиента
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Client exists in blocked list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockedClientDto'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found client in blocked list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Service error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Строковое описание ошибки
          example: Ошибка валидации
        code:
          type: string
          description: Код ошибки
          example: 400F
        uid:
          type: string
          description: Уникальный индентификатор ошибки
          example: a6c8116b-bb22-4322-b2d9-c3e9b8cd24c4
        fatal:
          type: boolean
          description: Критичность ошибки
          example: false
      description: Сообщение об ошибке
    UnblockedClientsDto:
      required:
        - clientIds
      type: object
      properties:
        clientIds:
          type: array
          description: Внешние id клиентов
          example:
            - 2C-FE32WE
            - 2C-FE3SE
          items:
            type: string
            description: Внешние id клиентов
            example: '["2C-FE32WE","2C-FE3SE"]'
      description: Разблокировать клиентов
    AddBlockedClientDto:
      required:
        - clientId
        - status
      type: object
      properties:
        status:
          type: string
          description: Причина блокировки клиента
          example: FRAUD
        clientId:
          type: string
          description: Внешний id клиента
          example: 2C-FE32WE
      description: Заблокировать клиента
    BlockedClientDto:
      required:
        - clientId
        - startDate
        - status
        - typeStatus
      type: object
      properties:
        clientId:
          type: string
          description: Внешний id клиента
          example: 2C-FE32WE
        startDate:
          type: string
          description: Начало блокировки
          format: date-time
        status:
          type: string
          description: Причина блокировки
          example: FRAUD
        typeStatus:
          type: string
          description: Добропорядочный клиент или нет
          example: NEGATIVE
          enum:
            - POSITIVE
            - NEGATIVE
      description: Информация о заблокированном клиенте
